obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= attestation_runtime_operations.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= boot_mode.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= caller_security.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= log.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= pluton.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= security_state.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= sm_generic.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= sm_user.o
obj-$(CONFIG_AZURE_SPHERE_SECURITY_MONITOR)	+= security_monitor.o
obj-$(CONFIG_AZURE_SPHERE_IO_CORE_COMM)	    += io_core_comm.o
obj-$(CONFIG_AZURE_SPHERE_RESET)            += azsphere_reset.o
obj-$(CONFIG_NULL_CONSOLE)                  += null_console.o

obj-$(CONFIG_MT3620_PLUTON)                 += mt3620_pluton.o
obj-$(CONFIG_PLUTON_REMOTEAPI)              += pluton_remoteapi.o
