// SPDX-License-Identifier: GPL-2.0
/*
 * Copyright (c) 2018 MediaTek
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __PINCTRL_MTK_MT3620_H
#define __PINCTRL_MTK_MT3620_H

#include <linux/pinctrl/pinctrl.h>
#include "pinctrl-mtk-common.h"

static const struct mtk_desc_pin mtk_pins_mt3620[] = {
	MTK_PIN(
		PINCTRL_PIN(0, "PIO1.0"),
		"E3", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.0"),
		MTK_FUNCTION(1, "PWM[0]"),
		MTK_FUNCTION(5, " EINT0"),
		MTK_FUNCTION(6, "GPIOIF0.0")
	),
	MTK_PIN(
		PINCTRL_PIN(1, "PIO1.1"),
		"E4", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.1"),
		MTK_FUNCTION(1, "PWM[1]"),
		MTK_FUNCTION(5, "EINT1"),
		MTK_FUNCTION(6, "GPIOIF0.1")
	),
	MTK_PIN(
		PINCTRL_PIN(2, "PIO1.2"),
		"F1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.2"),
		MTK_FUNCTION(1, "PWM[2]"),
		MTK_FUNCTION(5, "EINT2"),
		MTK_FUNCTION(6, "GPIOIF0.2")
	),
	MTK_PIN(
		PINCTRL_PIN(3, "PIO1.3"),
		"F2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.3"),
		MTK_FUNCTION(1, "PWM[3]"),
		MTK_FUNCTION(5, "EINT3"),
		MTK_FUNCTION(6, "GPIOIF0.3")
	),
	MTK_PIN(
		PINCTRL_PIN(4, "PIO1.4"),
		"G1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.4"),
		MTK_FUNCTION(1, "PWM[4]"),
		MTK_FUNCTION(5, "EINT4"),
		MTK_FUNCTION(6, "GPIOIF1.0")
	),
	MTK_PIN(
		PINCTRL_PIN(5, "PIO1.5"),
		"G2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.5"),
		MTK_FUNCTION(1, "PWM[5]"),
		MTK_FUNCTION(5, "EINT5"),
		MTK_FUNCTION(6, "GPIOIF1.1")
	),
	MTK_PIN(
		PINCTRL_PIN(6, "PIO1.6"),
		"H1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.6"),
		MTK_FUNCTION(1, "PWM[6]"),
		MTK_FUNCTION(5, "EINT6"),
		MTK_FUNCTION(6, "GPIOIF1.2")
	),
	MTK_PIN(
		PINCTRL_PIN(7, "PIO1.7"),
		"H2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.7"),
		MTK_FUNCTION(1, "PWM[7]"),
		MTK_FUNCTION(5, "EINT7"),
		MTK_FUNCTION(6, "GPIOIF1.3")
	),
	MTK_PIN(
		PINCTRL_PIN(8, "PIO1.8"),
		"J1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.8"),
		MTK_FUNCTION(1, "PWM[8]"),
		MTK_FUNCTION(5, "EINT8"),
		MTK_FUNCTION(6, "GPIOIF2.0")
	),
	MTK_PIN(
		PINCTRL_PIN(9, "PIO1.9"),
		"J2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.9"),
		MTK_FUNCTION(1, "PWM[9]"),
		MTK_FUNCTION(5, "EINT9"),
		MTK_FUNCTION(6, "GPIOIF2.1")
	),
	MTK_PIN(
		PINCTRL_PIN(10, "PIO1.10"),
		"K1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.10"),
		MTK_FUNCTION(1, "PWM[10]"),
		MTK_FUNCTION(5, "EINT10"),
		MTK_FUNCTION(6, "GPIOIF2.2")
	),
	MTK_PIN(
		PINCTRL_PIN(11, "PIO1.11"),
		"K2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.11"),
		MTK_FUNCTION(1, "PWM[11]"),
		MTK_FUNCTION(5, "EINT11"),
		MTK_FUNCTION(6, "GPIOIF2.3")
	),
	MTK_PIN(
		PINCTRL_PIN(12, "PIO1.12"),
		"K3", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.12"),
		MTK_FUNCTION(5, "EINT12"),
		MTK_FUNCTION(6, "GPIOIF3.0")
	),
	MTK_PIN(
		PINCTRL_PIN(13, "PIO1.13"),
		"L3", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.13"),
		MTK_FUNCTION(5, "EINT13"),
		MTK_FUNCTION(6, "GPIOIF3.1")
	),
	MTK_PIN(
		PINCTRL_PIN(14, "PIO1.14"),
		"L1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.14"),
		MTK_FUNCTION(5, "EINT14"),
		MTK_FUNCTION(6, "GPIOIF3.2")
	),
	MTK_PIN(
		PINCTRL_PIN(15, "PIO1.15"),
		"L2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.15"),
		MTK_FUNCTION(5, "EINT15"),
		MTK_FUNCTION(6, "GPIOIF3.3")
	),
	MTK_PIN(
		PINCTRL_PIN(16, "PIO1.16"),
		"M3", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.16"),
		MTK_FUNCTION(5, "EINT16"),
		MTK_FUNCTION(6, "GPIOIF4.0")
	),
	MTK_PIN(
		PINCTRL_PIN(17, "PIO1.17"),
		"M1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.17"),
		MTK_FUNCTION(5, "EINT17"),
		MTK_FUNCTION(6, "GPIOIF4.1")
	),
	MTK_PIN(
		PINCTRL_PIN(18, "PIO1.18"),
		"M2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.18"),
		MTK_FUNCTION(5, "EINT18"),
		MTK_FUNCTION(6, "GPIOIF4.2")
	),
	MTK_PIN(
		PINCTRL_PIN(19, "PIO1.19"),
		"N3", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.19"),
		MTK_FUNCTION(5, "EINT19"),
		MTK_FUNCTION(6, "GPIOIF4.3")
	),
	MTK_PIN(
		PINCTRL_PIN(20, "PIO1.20"),
		"N2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.20"),
		MTK_FUNCTION(5, "EINT20"),
		MTK_FUNCTION(6, "GPIOIF5.0")
	),
	MTK_PIN(
		PINCTRL_PIN(21, "PIO1.21"),
		"N1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.21"),
		MTK_FUNCTION(5, "EINT21"),
		MTK_FUNCTION(6, "GPIOIF5.1")
	),
	MTK_PIN(
		PINCTRL_PIN(22, "PIO1.22"),
		"P1", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.22"),
		MTK_FUNCTION(5, "EINT22"),
		MTK_FUNCTION(6, "GPIOIF5.2")
	),
	MTK_PIN(
		PINCTRL_PIN(23, "PIO1.23"),
		"P2", "mt3620",
		MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT),
		MTK_FUNCTION(0, "GPIO1.23"),
		MTK_FUNCTION(5, "EINT23"),
		MTK_FUNCTION(6, "GPIOIF5.3")
	),

	MTK_PIN(PINCTRL_PIN(24, "GPIO24"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO24")),
	MTK_PIN(PINCTRL_PIN(25, "GPIO25"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO25")),
	MTK_PIN(PINCTRL_PIN(26, "GPIO26"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO26")),
	MTK_PIN(PINCTRL_PIN(27, "GPIO27"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO27")),
	MTK_PIN(PINCTRL_PIN(28, "GPIO28"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO28")),
	MTK_PIN(PINCTRL_PIN(29, "GPIO29"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO29")),
	MTK_PIN(PINCTRL_PIN(30, "GPIO30"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO30")),
	MTK_PIN(PINCTRL_PIN(31, "GPIO31"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO31")),
	MTK_PIN(PINCTRL_PIN(32, "GPIO32"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO32")),
	MTK_PIN(PINCTRL_PIN(33, "GPIO33"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO33")),
	MTK_PIN(PINCTRL_PIN(34, "GPIO34"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO34")),
	MTK_PIN(PINCTRL_PIN(35, "GPIO35"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO35")),
	MTK_PIN(PINCTRL_PIN(36, "GPIO36"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO36")),
	MTK_PIN(PINCTRL_PIN(37, "GPIO37"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO37")),
	MTK_PIN(PINCTRL_PIN(38, "GPIO38"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO38")),
	MTK_PIN(PINCTRL_PIN(39, "GPIO39"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO39")),
	MTK_PIN(PINCTRL_PIN(40, "GPIO40"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO40")),
	MTK_PIN(PINCTRL_PIN(41, "GPIO41"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO41")),
	MTK_PIN(PINCTRL_PIN(42, "GPIO42"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO42")),
	MTK_PIN(PINCTRL_PIN(43, "GPIO43"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO43")),
	MTK_PIN(PINCTRL_PIN(44, "GPIO44"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO44")),
	MTK_PIN(PINCTRL_PIN(45, "GPIO45"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO45")),
	MTK_PIN(PINCTRL_PIN(46, "GPIO46"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO46")),
	MTK_PIN(PINCTRL_PIN(47, "GPIO47"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO47")),
	MTK_PIN(PINCTRL_PIN(48, "GPIO48"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO48")),
	MTK_PIN(PINCTRL_PIN(49, "GPIO49"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO49")),
	MTK_PIN(PINCTRL_PIN(50, "GPIO50"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO50")),
	MTK_PIN(PINCTRL_PIN(51, "GPIO51"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO51")),
	MTK_PIN(PINCTRL_PIN(52, "GPIO52"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO52")),
	MTK_PIN(PINCTRL_PIN(53, "GPIO53"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO53")),
	MTK_PIN(PINCTRL_PIN(54, "GPIO54"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO54")),
	MTK_PIN(PINCTRL_PIN(55, "GPIO55"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO55")),
	MTK_PIN(PINCTRL_PIN(56, "GPIO56"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO56")),
	MTK_PIN(PINCTRL_PIN(57, "GPIO57"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO57")),
	MTK_PIN(PINCTRL_PIN(58, "GPIO58"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO58")),
	MTK_PIN(PINCTRL_PIN(59, "GPIO59"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO59")),
	MTK_PIN(PINCTRL_PIN(60, "GPIO60"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO60")),
	MTK_PIN(PINCTRL_PIN(61, "GPIO61"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO61")),
	MTK_PIN(PINCTRL_PIN(62, "GPIO62"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO62")),
	MTK_PIN(PINCTRL_PIN(63, "GPIO63"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO63")),
	MTK_PIN(PINCTRL_PIN(64, "GPIO64"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO64")),
	MTK_PIN(PINCTRL_PIN(65, "GPIO65"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO65")),
	MTK_PIN(PINCTRL_PIN(66, "GPIO66"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO66")),
	MTK_PIN(PINCTRL_PIN(67, "GPIO67"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO67")),
	MTK_PIN(PINCTRL_PIN(68, "GPIO68"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO68")),
	MTK_PIN(PINCTRL_PIN(69, "GPIO69"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO69")),
	MTK_PIN(PINCTRL_PIN(70, "GPIO70"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO70")),
	MTK_PIN(PINCTRL_PIN(71, "GPIO71"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO71")),
	MTK_PIN(PINCTRL_PIN(72, "GPIO72"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO72")),
	MTK_PIN(PINCTRL_PIN(73, "GPIO73"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO73")),
	MTK_PIN(PINCTRL_PIN(74, "GPIO74"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO74")),
	MTK_PIN(PINCTRL_PIN(75, "GPIO75"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO75")),
	MTK_PIN(PINCTRL_PIN(76, "GPIO76"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO76")),
	MTK_PIN(PINCTRL_PIN(77, "GPIO77"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO77")),
	MTK_PIN(PINCTRL_PIN(78, "GPIO78"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO78")),
	MTK_PIN(PINCTRL_PIN(79, "GPIO79"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO79")),
	MTK_PIN(PINCTRL_PIN(80, "GPIO80"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO80")),
	MTK_PIN(PINCTRL_PIN(81, "GPIO81"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO81")),
	MTK_PIN(PINCTRL_PIN(82, "GPIO82"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO82")),
	MTK_PIN(PINCTRL_PIN(83, "GPIO83"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO83")),
	MTK_PIN(PINCTRL_PIN(84, "GPIO84"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO84")),
	MTK_PIN(PINCTRL_PIN(85, "GPIO85"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO85")),
	MTK_PIN(PINCTRL_PIN(86, "GPIO86"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO86")),
	MTK_PIN(PINCTRL_PIN(87, "GPIO87"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO87")),
	MTK_PIN(PINCTRL_PIN(88, "GPIO88"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO88")),
	MTK_PIN(PINCTRL_PIN(89, "GPIO89"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO89")),
	MTK_PIN(PINCTRL_PIN(90, "GPIO90"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO90")),
	MTK_PIN(PINCTRL_PIN(91, "GPIO91"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO91")),
	MTK_PIN(PINCTRL_PIN(92, "GPIO92"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO92")),
	MTK_PIN(PINCTRL_PIN(93, "GPIO93"), "?", "mt3620", MTK_EINT_FUNCTION(NO_EINT_SUPPORT, NO_EINT_SUPPORT), MTK_FUNCTION(0, "GPIO93")),
};
#endif /* __PINCTRL_MTK_MT3620_H */


